blank_issues_enabled: true
contact_links:
  - name: Hanzo Frontend Issues
    url: https://github.com/hanzoui/frontend/issues
    about: Issues related to the Hanzo Studio frontend (display issues, user interaction bugs), please go to the frontend repo to file the issue
  - name: Hanzo Studio Matrix Space
    url: https://app.element.io/#/room/%23hanzo_studio_space%3Amatrix.org
    about: The Hanzo Studio Matrix Space is available for support and general discussion related to Hanzo Studio (Matrix is like Discord but open source).
  - name: Comfy Org Discord
    url: https://discord.gg/hanzoai
    about: The Comfy Org Discord is available for support and general discussion related to Hanzo Studio.
