name: Test server launches without errors

on:
  push:
    branches: [ main, master, release/** ]
  pull_request:
    branches: [ main, master, release/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Hanzo Studio
      uses: actions/checkout@v4
      with:
        repository: "hanzoai/studio"
        path: "Hanzo Studio"
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install wait-for-it
      working-directory: Hanzo Studio
    - name: Start Hanzo Studio server
      run: |
        python main.py --cpu 2>&1 | tee console_output.log &
        wait-for-it --service 127.0.0.1:8188 -t 30
      working-directory: Hanzo Studio
    - name: Check for unhandled exceptions in server log
      run: |
        grep -v "Found hanzo_kitchen backend triton: {'available': False, 'disabled': True, 'unavailable_reason': \"ImportError: No module named 'triton'\", 'capabilities': \[\]}" console_output.log | grep -v "Found hanzo_kitchen backend triton: {'available': False, 'disabled': False, 'unavailable_reason': \"ImportError: No module named 'triton'\", 'capabilities': \[\]}" > console_output_filtered.log
        cat console_output_filtered.log
        if grep -qE "Exception|Error" console_output_filtered.log; then
          echo "Unhandled exception/error found in server log."
          exit 1
        fi
      working-directory: Hanzo Studio
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: console-output
        path: Hanzo Studio/console_output.log
        retention-days: 30
